# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.52python.cn
date_format: "ordinal"
title: Accelerator
subtitle: "我无法改变世界..."
description: "Accelerator的个人博客"
keywords: Accelerator,seven
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Accelerator
organization: 52python.cn
organization_url: https://blog.52python.cn
github_username: Matrixseven
location: Beijing, China
email: hacker.kill07@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: matrixseven/matrixseven.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: matrixseven
    repo: blog-comments
    oauth:
        client_id: 833bda0353417cc694b0
        client_secret: 8a3e24a7889cfb4cdf4382ccc81237f6d2885e9d
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: matrixseven
    repo: blog-comments
    clientID: 833bda0353417cc694b0
    clientSecret: 8a3e24a7889cfb4cdf4382ccc81237f6d2885e9d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
